### ISSUE TITLE
Moves page  shows up empty

### ISSUE THREAD

**Issue by RenatoFerrara2000** [gcoulby/IronswornCompanion#14]
Moves page shows up empty
<img width="641" alt="Screenshot 2024-04-02 at 22 16 14" src="https://github.com/gcoulby/IronswornCompanion/assets/80359187/e9ba46f6-055b-4c49-a490-7a8e07abe5f6">

**Comment by RenatoFerrara2000** [comment]
The error seems to be due to the app.js fetching data from  https://raw.githubusercontent.com/rsek/datasworn/master/ironsworn_moves.json 
 
Unfortunately this link is not available due to rsek update, but still by changing the fetch to the legacy branch like this:
https://raw.githubusercontent.com/rsek/datasworn/legacy/ironsworn_moves.json  the error  should be solved

**Comment by gcoulby** [comment]
This has now been resolved, thank your for pointing it out.
